# Generated by Django 5.1.7 on 2025-03-18 08:03

import django.db.models.deletion
import simulation.util
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('lifespan', models.IntegerField()),
                ('fit_threshold', models.FloatField()),
                ('average_fitness', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.FloatField(default=simulation.util.generate_normalized_value)),
                ('speed', models.FloatField(default=simulation.util.generate_normalized_value)),
                ('intelligence', models.FloatField(default=simulation.util.generate_normalized_value)),
                ('fitness', models.FloatField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('population', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='simulation.population')),
            ],
        ),
    ]
